### ISSUE TITLE
Canada Post Key format  

### ISSUE THREAD

**Issue by vcb-xrmvision** [dotnetprog/PCF-CanadaPost-AddressComplete#1]
The control doesn't seem to return any result.
If I inspect the service response I obtain : 

0: {Error: "2", Description: "Unknown key",…}
Cause: "The key you are using to access the service was not found."
Description: "Unknown key"
Error: "2"
Resolution: "Please check that the key is correct. It should be in the form AA11-AA11-AA11-AA11."

I obtained a key from canada post but the format is  (username : password) 
username 16 car
password 23 car 

![image](https://user-images.githubusercontent.com/58830932/84393342-75b82500-abc9-11ea-81dc-a38f93f3d38f.png)

I tried to split the user name with dash like this format AA11-AA11-AA11-AA11but I still receive the same message

**Comment by dotnetprog** [comment]
Please follow the step belows to have a proper api key. 

![image](https://user-images.githubusercontent.com/24593889/84395621-17407600-abcc-11ea-9cb1-310212289248.png)
![image](https://user-images.githubusercontent.com/24593889/84395891-2cb5a000-abcc-11ea-8f4b-c3ec385341cc.png)
![image](https://user-images.githubusercontent.com/24593889/84396418-55d63080-abcc-11ea-970a-e8b7171ada0c.png)
