### ISSUE TITLE
Control Format (width/height)

### ISSUE THREAD

**Issue by jyin191** [dotnetprog/PCF-CanadaPost-AddressComplete#5]
Is there a way to configure the width/height of the control?

in the following screenshot, the control is always limited to a certain size, just wondering if it can be adjusted.

Thanks

![image](https://user-images.githubusercontent.com/67660654/87464837-a1636c00-c5c8-11ea-95d8-d0d96e74c6be.png)

**Comment by dotnetprog** [comment]
Hi,

Thanks for your feedback :) I managed to make the textbox look as if it was out of the box , with same behavior. Please install the latest solution in the solution directory :)

Here's a sample:
![image](https://user-images.githubusercontent.com/24593889/87841431-135ede00-c873-11ea-9e3f-28d693a37601.png)
![image](https://user-images.githubusercontent.com/24593889/87841445-296c9e80-c873-11ea-9407-f4f75e6493db.png)

**Comment by dotnetprog** [comment]
the issue is resolved?

**Comment by jyin191** [comment]
it worked beautifully - thanks for your quick actions!
